### ISSUE TITLE
Script stopped working (Jean_b.py)

### ISSUE THREAD

**Issue by kaufmannVincent** [nickmitchko/wikileaks#1]
Hello there, any explanation why the Jean scripts stopped working all the sudden?
Would you be able to get it working again? Could i be of any help?

Thx :)

**Comment by nickmitchko** [comment]
Can you show me the error message you are getting?

**Comment by kaufmannVincent** [comment]
Error is:

root@downloader:/home/ubuntu/wikileaks# python jean_b.py 54e48e5f5c656b26c3bca14a8c95aa583d07ebe84dde3b7dd4a78f4e4186e713 bitcoin.pdf
Traceback (most recent call last):
  File "jean_b.py", line 43, in <module>
    dataout += unhexlify(c.encode('utf8'))
TypeError: Odd-length string

**Comment by kaufmannVincent** [comment]
Does it still work for you? Could you confirm it?

**Comment by kaufmannVincent** [comment]
Is it possible to use a Local copy of the Blockchain (/blocks folder) to use this script?

**Comment by kaufmannVincent** [comment]
I added this and the SSL error is suppressed.

import urllib2
>>>import ssl

>>>ctx = ssl.create_default_context()
>>>ctx.check_hostname = False
>>>ctx.verify_mode = ssl.CERT_NONE

>>>transaction = str(sys.argv[1])
>>>data = urllib2.urlopen("https://blockchain.info/tx/"+transaction+"?show_adv=true&quot;", >>>context=ctx)

Now im getting:
Traceback (most recent call last):
  File "j.py", line 48, in <module>
    dataout += unhexlify(c.encode('utf8'))
TypeError: Odd-length string

**Comment by nickmitchko** [comment]
Hmmm. There was an external change to how blockchain.info is served on the web. Look at https://github.com/nickmitchko/wikileaks/blob/5aaf2d9a5c4d046cb13da116acde9bd00642f3cb/wltr9.py

if you want to try and modify for using a local blockchain.

**Comment by kaufmannVincent** [comment]
Perhaps possible to use an alternative to blockchain.info?
